name: Selfhosted  # workflow name

on: [push]  
jobs: 
  hello:
     runs-on: [self-hosted, linux] # crerated a self hosted runner 
     steps: #stages 
       - name: step1 
         run: echo "Self-Hosted-Runner"
       - name: step2
         run: echo "hello Github Actions"



